---
driver:
  name: vagrant
  config:
    boot_timeout: 1200
<% if ENV['TEAMCITY'] == '1' %>
  synced_folders:
    - ['.junit', '/.junit']
<% end %>

provisioner:
  name: chef_solo
  require_chef_omnibus: '12.0.3'

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt::default]
  - name: debian-6.0.10
    run_list:
    - recipe[apt::default]
  - name: debian-7.8
    run_list:
    - recipe[apt::default]
  - name: centos-6.6
    run_list:
    - recipe[yum::default]
  - name: centos-7.0
    run_list:
    - recipe[yum::default]
  - name: opentable/win-2008r2-standard-amd64-nocm
    os_type: windows
    shell_type: powershell
    run_list:
    - recipe[windows::default]
    transport:
      name: winrm
  - name: opentable/win-2012r2-standard-amd64-nocm
    os_type: windows
    shell_type: powershell
    run_list:
    - recipe[windows::default]
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[nxlog::default]
      - recipe[nxlog::test_kitchen_log_file]
    attributes:
