language: ruby
gemfile:
  - Gemfile
rvm:
  - 1.9.3
  - 2.1
  - 2.2
bundler_args: "--without integration"
before_script: bundle exec berks install
script: bundle exec strainer test -e kitchen
notifications:
  email:
    - travis-ci@widgit.com
  hipchat:
    room:
      secure: aeMN+zb7BksIrr2i0Lj3mL2ZlLhrtXDtNFDCJG1yFWx/VuT49g9iM2Y3cNjASA6SJmXWN6jpLFwYfQ/IjyiaASPTogLxIzolBG73QCN9NTQ+b0YZSg/xi4nDpa5rXHABemlnA1GEYJQBSaJRaEePNTFxLGDjOygK6IeDNY5Pn1c=
